// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilverProcessingApp.Models;

namespace SilverProcessingApp.Migrations.Silver
{
    [DbContext(typeof(SilverContext))]
    partial class SilverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SilverProcessingApp.Models.BuyingRawSilver", b =>
                {
                    b.Property<int>("SilverCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateofPurchase")
                        .HasColumnType("date");

                    b.Property<decimal>("GST")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GramsPerUnit")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("IPADDRESS")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageName2")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageName3")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageName4")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageName5")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mass")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("NoSilverUnits")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PCNAME")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RawSilverQuantity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("SilverValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SupplierPhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("SilverCode");

                    b.ToTable("BuyingRawSilver");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.EmployeeDetails", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.ScrapSilverPurityCalculatorJobDetails", b =>
                {
                    b.Property<int>("SilverCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ExpectedfinalPurity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FinalPurity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FinalValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("IPADDRESS")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("PCNAME")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentageTomakepure")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Pido")
                        .HasColumnType("int");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("PureSilver")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("QuantityinGms")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("ScrapSilverPurityCalculatorJobDetailsSilverCode")
                        .HasColumnType("int");

                    b.Property<int?>("ScrapSilverPurityConvertorJobPid")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SilverCode");

                    b.HasIndex("ScrapSilverPurityCalculatorJobDetailsSilverCode");

                    b.HasIndex("ScrapSilverPurityConvertorJobPid");

                    b.ToTable("ScrapSilverPurityCalculatorJobDetails");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.ScrapSilverPurityConvertorJob", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Dateofinput")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ExpectedfinalPurity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FromBuyer")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IPADDRESS")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("DateTime");

                    b.Property<string>("PCNAME")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductNo")
                        .HasColumnType("int");

                    b.Property<string>("ToEndUser")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Pid");

                    b.ToTable("ScrapSilverPurityConvertorJob");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.SellOutDetails", b =>
                {
                    b.Property<int>("SelloutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerPhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Selloutdate")
                        .HasColumnType("date");

                    b.Property<decimal>("Selloutvalue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Soldby")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("SelloutId");

                    b.ToTable("SellOutDetails");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.SilverArticles", b =>
                {
                    b.Property<int>("SilverArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateofProcess")
                        .HasColumnType("date");

                    b.Property<decimal>("GST")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MakingCharges")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Processby")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("RawSilverQuantity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("SilverValue")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TypeofSilverArticle")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Wastage")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("SilverArticleId");

                    b.ToTable("SilverArticles");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.SupplierDetails", b =>
                {
                    b.Property<int>("SupplierCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountPayed")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("QuantityBuyed")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SupplierPhoneNo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("SupplierCode");

                    b.ToTable("SupplierDetails");
                });

            modelBuilder.Entity("SilverProcessingApp.Models.ScrapSilverPurityCalculatorJobDetails", b =>
                {
                    b.HasOne("SilverProcessingApp.Models.ScrapSilverPurityCalculatorJobDetails", null)
                        .WithMany("PurityCalculators")
                        .HasForeignKey("ScrapSilverPurityCalculatorJobDetailsSilverCode");

                    b.HasOne("SilverProcessingApp.Models.ScrapSilverPurityConvertorJob", null)
                        .WithMany("PurityCalculators")
                        .HasForeignKey("ScrapSilverPurityConvertorJobPid");
                });
#pragma warning restore 612, 618
        }
    }
}
